### PR TITLE
Merge setup-erlang in

### LINKED ISSUE #15: Bad version results in confusing error message
I accidentally tried to use an Elixir version that doesn't exist, `elixir-version: 11.1.1`, and the error message given is "Error: Cannot read property 'includes' of undefined" instead of saying the Elixir version does not exist.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I'll make a self-review after which I welcome yours.

This description may see actions added to it if decisions are yet to be made.

**Note**: where I previously had `erlang`, I now have `otp` (as per what was present in this action already). Lemme know if I should rename anything.

---

I add:
- JavaScript -based linting
- a CI process to make sure what we're releasing doesn't miss anything
- `rebar3`-version -based elements to CI
- input `rebar3-version` to the action (everything else remains untouched)
- tests for added stuff
- a `rebar3` installation (`bash`) script that fetches versions from GitHub
- some tests for robustness
- error messages (some `console`, some `core`)
- version output to the install actions (shell scripts) to make it easier to debug (and not force consumers to look at the outputs)

I change:
- licenses to `yarn` -based (thus deleting tons of files from the repo, and adding 3RD PARTY LICENSES)
- Markdown as per linting
- phrasing "OTP" to "Erlang/OTP", by default (mostly everywhere if not everywhere)
- shell scripts as per linting
- input `elixir-version` so it becomes optional
- some internals (with test specific code) so it's easier to test locally
- CI to make sure it breaks when it should
- the code as to separate "production" from "test"
- the shell scripts in order to make the more closely related (helps reason for updates)
- exception handling to cover all the cases
- `test.yml` ever so slightly in order to make sure backward compatibility is kept while adding new CI stuff
- `action.yml` ever so slightly

I remove:
- `licensed`-based license management (and associated assets)
- stuff that linting was complaining about not being used

All of this means the action should be fully backward compatible.

Also, closes #15.

### CODE REVIEW

File: src/installer.js [hunk 1]
```diff
@@ -1,8 +1,16 @@
 const {exec} = require('@actions/exec')
 const path = require('path')
-const semver = require('semver')
 
-module.exports = {installElixir, installOTP}
+/**
```
Comment (paulo-ferraz-oliveira) [inline src/installer.js:4]: Move for consistency only (can move back if you prefer). I wanted, for my sanity, to have OTP > Elixir > rebar3 everywhere.

File: src/setup-elixir.js [hunk 2]
```diff
@@ -1,65 +1,97 @@
...
   promises: {readFile},
 } = require('fs')
 
-main().catch(err => {
+main().catch((err) => {
   core.setFailed(err.message)
 })
 
 async function main() {
-  checkPlatform()
```
Comment (paulo-ferraz-oliveira) [inline src/setup-elixir.js:17]: Same operations as performed, as per testing. I just made some stuff optional and moved other stuff around to follow the Erlang > Elixir > rebar3 exposed previously

**Comment by paulo-ferraz-oliveira** [comment]
Self-review is finished. Bash away.

**Comment by paulo-ferraz-oliveira** [comment]
I'll make the test fixes in a separate commit so as to not disturb the "base". (I'll keep squashing on top of that one until everything's fine)

File: src/setup-elixir.js [hunk 3]
```diff
@@ -73,22 +105,20 @@ function getRunnerOSVersion() {
...
-    .filter(str => str.match(semverRegex))
-    .map(str => str.match(semverRegex)[1])
+    .filter((str) => str.match(semverRegex))
+    .map((str) => str.match(semverRegex)[1])
 
   const version = getVersionFromSpec(spec, semverVersions)
   const gitRef = version ? `v${version}` : spec
   const otpMatch = otpVersion.match(/^OTP-([\.\d]+)/)
 
-  if (otpMatch != null && versions.get(gitRef).includes(otpMatch[0])) {
```
Comment (paulo-ferraz-oliveira) [inline src/setup-elixir.js:90]: This one's odd: found it after fixing the tests for local deployment.
The input `otpVersion` has to have `OTP-` otherwise `otpMatch` is null (tests fail).
On the other hand, if that's the case, `otpMatch[0]` will contain the `OTP-` prefix.

**Note**: I can only assume this was dead code.

File: __tests__/setup-elixir.test.js [hunk 4]
```diff
@@ -1,21 +1,39 @@
-const {getElixirVersion} = require('../src/setup-elixir')
```
Comment (paulo-ferraz-oliveira) [inline __tests__/setup-elixir.test.js:1]: The Elixir ones were broken, but CI wasn't running them either 😄

File: src/setup-elixir.js (hunk 3 above)
Comment (starbelly) [reply src/setup-elixir.js:90]: This was added by @ericm a few months ago, it surely must have been added for a reason.  It looks like it's just being defensive and that makes sense to me for the case. 

https://github.com/erlef/setup-elixir/commit/4edd0cd12d3a1a7052d40c1e51d669262e3c7b3b

File: dist/.github1/elixir.json [hunk 5]
```diff
@@ -0,0 +1,46 @@
+{
```
Comment (starbelly) [inline dist/.github1/elixir.json:1]: I assume `.github1` is a temporary directory?

File: dist/install-otp1 [hunk 6]
```diff
@@ -0,0 +1,15 @@
+#!/bin/bash
```
Comment (starbelly) [inline dist/install-otp1:1]: Same as `.github1` is this file an artifact or moving things around?

File: src/setup-elixir.js [hunk 7]
```diff
@@ -103,15 +134,14 @@ function getVersionFromSpec(spec, versions) {
   }
 }
 
-async function getOtpVersions(osVersion) {
-  const result = await get(
-    `https://repo.hex.pm/builds/otp/${osVersion}/builds.txt`
-  )
+async function getOTPVersions(osVersion) {
+  const result = await get(`https://repo.hex.pm/builds/otp/${osVersion}/builds.txt`,
+    'otp_builds.txt')
```
Comment (ericmj) [inline src/setup-elixir.js:139]: What is the purpose of the separate test file?

**Review by ericmj — COMMENTED** [review]
I've done a first pass on this and left some comments. Great work!

There seems to be some `dist/` files and directories that seems duplicated and end with `1` in the name. Can you look into that?

File: src/setup-elixir.js (hunk 3 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:90]: ... which is why I find it odd 😄 

`versions.get(gitRef)`, as is, will always fail to include `otpMatch[0]`; with `[1]` though I expect to fix the behaviour as to what we need/want. 

@ericmj?

File: dist/.github1/elixir.json (hunk 5 above)
Comment (paulo-ferraz-oliveira) [reply dist/.github1/elixir.json:1]: Nope. This `dist` stuff is not handled "by hand". It's generated with `npm run build`. I also found this odd (and asked around for a better explanation), but couldn't get one or find one. I just trust it `ncc` knows what it's doing and that if a fix comes around we'll benefit from it, in the future.

File: dist/install-otp1 (hunk 6 above)
Comment (paulo-ferraz-oliveira) [reply dist/install-otp1:1]: Same reply as before 😄

**Comment by paulo-ferraz-oliveira** [comment]
> There seems to be some dist/ files and directories that seems duplicated and end with 1 in the name. Can you look into that?

I have looked into that. I could remove them by hand, but then `ncc build` would just recreate them (I'm not doing anything special here[1], and I've tried recreating the project from scratch; they still get generated). Some kind of `ncc` magic I don't know how to solve.

---

[1] @ericmj, let me know if, locally, you run `ncc build` (after deleting `dist`) and get different results (it might be a Mac OS X thing, I don't know).

**Comment by ericmj** [comment]
If the files end with `1` it's not a big issue but I think the duplicate files can cause issues.

Can you try to find the change that is causing the duplicates since we didn't have them before?

File: src/setup-elixir.js (hunk 7 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:139]: `builds.txt` lists Elixir versions, `otp_builds.txt` lists Erlang versions. They come from different sources in Hex.pm. I don't understand the question, probably. If the input is different (`builds.txt` for Elixir v. `builds.txt` from Erlang) should the tests', also?

File: src/setup-elixir.js [hunk 8]
```diff
@@ -1,65 +1,98 @@
...
+    core.setOutput('rebar3-version', otpVersion)
+  }
 
-  if (installRebar === 'true') await exec('mix local.rebar --force')
-  if (installHex === 'true') await exec('mix local.hex --force')
+  // mix - optional
+  if (elixirSpec) {
+    process.env.PATH += `:${process.env.RUNNER_TEMP}/.setup-elixir/otp/bin`
+    process.env.PATH += `:${process.env.RUNNER_TEMP}/.setup-elixir/elixir/bin`
+    process.env.PATH += `:${process.env.RUNNER_TEMP}/.setup-elixir/rebar3/bin`
```
[the remark this answers is not in the document]
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:58]: Sure. It's in the wrong section 😄. I just wanted to be complete, I'll move these to the appropriate functions (that you asked me to create).

File: src/setup-elixir.js [hunk 9]
```diff
@@ -1,65 +1,98 @@
...
-  core.setOutput('elixir-version', elixirVersion)
-  core.setOutput('osVersion', osVersion)
+    let installRebar = core.getInput('install-rebar')
+    installRebar = installRebar == null ? 'true' : installRebar
+    installRebar && await exec('mix local.rebar --force')
+
+    let installHex = core.getInput('install-hex')
+    installHex = installHex == null ? 'true' : installHex
+    installHex && await exec('mix local.hex --force')
+  }
```
[the remark this answers is not in the document]
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:67]: Sure.

**Comment by paulo-ferraz-oliveira** [comment]
> Can you try to find the change that is causing the duplicates since we didn't have them before?

You mean go over `ncc` and try to figure out if this is a bug? I'm not quite sure how to do it otherwise, since I've looked (and couldn't find) any specific options or different way of doing things. (also, did you test it locally?)

**Comment by ericmj** [comment]
I can't test locally currently.

It looks like the package is deprecated https://www.npmjs.com/package/@zeit/ncc. You can try the package that replaces it.

**Comment by ericmj** [comment]
> You mean go over ncc and try to figure out if this is a bug?

We don't have duplicates in `dist/` in `main` currently so something has changed that is causing them to be generated. Either in the changes in this PR or elsewhere.

**Comment by paulo-ferraz-oliveira** [comment]
> I can't test locally currently.
> 
> It looks like the package is deprecated https://www.npmjs.com/package/@zeit/ncc. You can try the package that replaces it.

I thought I'd updated it to `vercel`. In any case, I get the same behaviour locally with that new package. I can dig further, but I wouldn't want to have to path `ncc` if it comes to that.

(just check, and I did update to `vercel` latest - actually IIRC I updated all the node.js deps to latest)

**Comment by paulo-ferraz-oliveira** [comment]
> > You mean go over ncc and try to figure out if this is a bug?
> 
> We don't have duplicates in `dist/` in `main` currently so something has changed that is causing them to be generated. Either in the changes in this PR or elsewhere.

I agree. Something has changed. But even in `setup-erlang` I got the duplicates and I still hadn't mixed that with `setup-elixir`. Let me try to find some time to tackle it, later.

File: src/setup-elixir.js (hunk 7 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:139]: Does this make sense? Can I Resolve it, or do you want some type of change?

File: src/setup-elixir.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:67]: Found a bug while doing it, too. 
```javascript
core.setOutput('rebar3-version', otpVersion)
```
😄

File: src/setup-elixir.js (hunk 7 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:148]: I'll make this more explicit by renaming the files.

File: src/setup-elixir.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: (replying in the main thread)

File: src/setup-elixir.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: (replying in the main thread)

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/erlef/setup-elixir/pull/9/commits/b58b61c8912cd59f8b91d968bf952ec3f86de1f3 addresses comments:
* https://github.com/erlef/setup-elixir/pull/9#discussion_r595366793 (r595366793)
* https://github.com/erlef/setup-elixir/pull/9#discussion_r595366917 (r595366917)

I'm still missing a follow-up on:
- [ ] https://github.com/erlef/setup-elixir/pull/9#discussion_r595905293 (r595905293)
- [ ] https://github.com/erlef/setup-elixir/pull/9#discussion_r595919249 (r595919249)
- [ ] the whole `ncc build` v. duplicate files issue

**Comment by paulo-ferraz-oliveira** [comment]
I may have traced down the "duplicate `dist` stuff" to the fact the `__tests__` folder includes and gets included by `setup-elixir.js`.

File: package.json [hunk 10]
```diff
@@ -4,23 +4,35 @@
...
+    "@actions/exec": "1.0.1",
+    "semver": "7.3.4"
   },
   "devDependencies": {
-    "@zeit/ncc": "^0.22.1",
+    "@vercel/ncc": "0.27.0",
+    "eslint": "7.22.0",
+    "eslint-config-google": "0.14.0",
     "husky": "^4.2.5",
-    "prettier": "^2.0.5"
```
Comment (paulo-ferraz-oliveira) [inline package.json:24]: @ericmj, I removed this. I'm not really sure it's useful. Lemme know.

File: src/setup-elixir.js (hunk 3 above)
Comment (ericmj) [reply src/setup-elixir.js:90]: If you are changing it can you add a test for it to verify that it works?

File: src/setup-elixir.js (hunk 7 above)
Comment (ericmj) [reply src/setup-elixir.js:151]: I am wondering why we need a separate test file when we can fetch it from the source repo.hex.pm. I would like to avoid mixing test and production code if possible.

**Comment by ericmj** [comment]
> I may have traced down the "duplicate dist stuff" to the fact the __tests__ folder includes and gets included by setup-elixir.js.

Why are the test files included?

File: src/setup-elixir.js (hunk 3 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:90]: Well, the tests did fail because of it (but they weren't running in CI, as explained [here](https://github.com/erlef/setup-elixir/issues/8#issue-831022789): test.yml contains npm test (that's "failing", even though not signalling CI properly)). Which is why it was changed. Want me to create a more low level unit test?

File: src/setup-elixir.js (hunk 7 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:151]: So... we're fetching versions dynamically, right? And then we have expressions like ^1.10, which will resolve to the latest published (I got this error yesterday, which is why I fixed the tests to use `elixir_builds.txt`). If we depend on an external source, there's less correctness in repeatability (i.e. you don't know how/when a change in an external resource will affect you). I don't mind moving the code away from it, though (e.g. by exposing the route as a parameter instead of juggling env. variables).

**Comment by paulo-ferraz-oliveira** [comment]
> > I may have traced down the "duplicate dist stuff" to the fact the **tests** folder includes and gets included by setup-elixir.js.
> 
> Why are the test files included?

I'm not actually sure (since have little knowledge of `ncc`) but believe it's linked to that by the fact we're using the `.txt` files. As per a more recent comment, I'll try to separate those and see what happens.

**Comment by paulo-ferraz-oliveira** [comment]
I was able to solve the "duplicate file" thing by completely separating test code from production code (when I started working on this the mix was already there, and I wrongly continued working on top of that).
I was able to simplify both the production code and test.yml, as well as improving maintenance on the test code.
I hopefully got everything in here, so will now only (again!) concentrate on fixing per test results.

File: src/setup-elixir.js (hunk 3 above)
Comment (starbelly) [reply src/setup-elixir.js:90]: It definitely would not hurt @paulo-ferraz-oliveira

File: package.json (hunk 10 above)
Comment (starbelly) [reply package.json:24]: @paulo-ferraz-oliveira IMO it's useful if we need to format code, which I hope we would be.

Comment (paulo-ferraz-oliveira) [reply package.json:24]: The way it was, IIRC, not only was the code not formatted (the one that was pushed) but the result was not taken into account. I don't mind adding something that actually does in-place code format replacement (which could be tested in CI), but as-was it was kinda limited.

File: src/setup-elixir.js (hunk 3 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:90]: Sure, but let me rephrase: as-is the code that was changed IS being tested. It wasn't previously, which is what the tests (the fact that `npm test` started being used) actually helped find/fix.

Comment (starbelly) [reply src/setup-elixir.js:90]: I see. If it's covered, then it's covered IMO.

Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:90]: I added more tests (with OTP-, without OTP, failing installations, and such) so we get better coverage.
I also added `core.error` and `core.warning` where I found appropriate to ease consumption of the action.

File: src/setup-elixir.js (hunk 7 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: Production code is separated from test code as much as possible.

File: package.json (hunk 10 above)
Comment (paulo-ferraz-oliveira) [reply package.json:24]: I've added this again. I'm afraid this increased the code to review by a bit, since it touched stuff that was previously unformatted. At the same time, it'll (most constantly) imply having to tweak the linter and prettier config. files at the same time.

**Comment by paulo-ferraz-oliveira** [comment]
Lemme know if the current status is "OK for merge". I'd like to test it in a few projects before moving to `master` but am yet unaware of how to target a specific branch for an action.

File: src/install-otp [hunk 11]
```diff
@@ -2,11 +2,18 @@
...
-wget -q -O otp.tar.gz https://repo.hex.pm/builds/otp/${2}/${1}.tar.gz
-mkdir -p .setup-elixir/otp
-tar zxf otp.tar.gz -C .setup-elixir/otp --strip-components=1
-rm otp.tar.gz
-.setup-elixir/otp/Install -minimal $(pwd)/.setup-elixir/otp
-echo "$(pwd)/.setup-elixir/otp/bin" >> $GITHUB_PATH
+cd "$RUNNER_TEMP"
+
+OS=${1}
+FILE_INPUT=${2}.tar.gz
```
Comment (starbelly) [inline src/install-otp:8]: Love the clarity here, I was just looking at this 💯

Comment (paulo-ferraz-oliveira) [reply src/install-otp:8]: Yeah, I feel $1, $2, etc. in `bash` doesn't really help, most of the time.

**Comment by paulo-ferraz-oliveira** [comment]
I will revert `[1]` to `[0]` in the match procedure. In any case, `versions` is

```
  'v1.8.0' => [ '20', '21', '22' ],
  'v1.8.0-rc.0' => [ '20', '21', '22' ],
  'v1.8.0-rc.1' => [ '20', '21', '22' ],
  'v1.8.1' => [ '20', '21', '22' ],
  'v1.8.2' => [ '20', '21', '22' ],
  'v1.9' => [ '20', '21', '22' ],
  'v1.9.0' => [ '20', '21', '22' ],
  'v1.9.0-rc.0' => [ '20', '21', '22' ],
  'v1.9.1' => [ '20', '21', '22' ],
  'v1.9.2' => [ '20', '21', '22' ],
  'v1.9.3' => [ '20', '21', '22' ],
  'v1.9.4' => [ '20', '21', '22' ]
```

so I fail to see how we can match `OTP-...` in that.

**Comment by paulo-ferraz-oliveira** [comment]
Also, let's assume https://repo.hex.pm/builds/elixir/v1.10.3.zip exists (in which case, `OTP-` is not required, all the tests pass, but the code is still wrong). If you try that link it works, so my (again) **strong** suspicion is that we're potentially not targeting the OTP we think we are. @starbelly, can you add a `erl -version` in `erlef/website` and then compare the emulator version with what you're expecting?

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira yeah, I get back 11.1.2 for erlef/website. https://github.com/erlef/website/pull/296/checks?check_run_id=2162938782 . See compile task.

**Comment by starbelly** [comment]
Oversight on my end I looked at all this earlier :  https://github.com/erlef/setup-elixir/blob/885971a72ed1f9240973bd92ab57af8c1aa68f24/src/setup-elixir.js#L23

☝️  `otpMajor` as returned from `getElixirVersion()` is only used for outputting info to the user. Not for fetching as can be seen a few lines below here 👇  : https://github.com/erlef/setup-elixir/blob/885971a72ed1f9240973bd92ab57af8c1aa68f24/src/setup-elixir.js#L35

**Comment by paulo-ferraz-oliveira** [comment]
OK, so this means (in `main`), we're pulling:

1. the correct Erlang/OTP with script `install-otp`,
2. Elixir from Hex.pm without caring for Erlang/OTP version (e.g. https://repo.hex.pm/builds/elixir/v1.11.2.zip).
^ this is the scenario with `[0]` in the `match`.

It also means that (in this pull request), we're pulling:
1. the correct Erlang/OTP with script `install-otp`,
2. Elixir from Hex.pm caring for the Erlang/OTP version (e.g. https://repo.hex.pm/builds/elixir/v1.11.2-otp-23.zip).
^ this is the scenario with `[1]` in the `match`.

I believe the latter is more correct, right? And by "do away with this code" you mean not returning null but actually an error, right?

**Comment by paulo-ferraz-oliveira** [comment]
I'd added stuff like
```javascript
  if (version == null) {
    core.warning(
      `Requested Erlang/OTP version (from spec ${spec}) not found in build listing ` +
        `${otpBuildsListing}`,
    )
  }
```

to the verifications of available versions, for Erlang/OTP, Elixir and `rebar3`. It's probably best to just throw an exception there, instead of a `warning` (again, I didn't want to break behaviour because I was unsure of previous requirements).

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, @ericmj, I made the code throw (it's caught by the `main()` promise) when a version is not found (and made sure we had tests for these) instead of working around what has apparently been a hidden bug.

**Comment by paulo-ferraz-oliveira** [comment]
I'm removing the tests I'd added for mix. Reason is the following: when you `require` the index file, depending on the input stuff get's installed (via `main()`), which means those tests will not fail (in unit, at least).

**Comment by starbelly** [comment]
>  And by "do away with this code" you mean not returning null but actually an error, right?

Scratch that, it's useful to get the requested version of elixir compiled for a specific OTP major version. Take for example, when OTP 24 lands. With the bug in place, if you request elixir x.x.x and you say OTP 24, but we grab x.x.x compiled for an earlier version of OTP (which would be compat with OTP 24), there could be subtle differences in behavior and performance and this would be surprising IMO. 

Best effort if you will. But let's fix the bug 😁. I think if you adjust the code to use `[1]` for the look up in `includes` but return `[0]` that will do it. 

I'll take another pass at review later today.

**Comment by paulo-ferraz-oliveira** [comment]
I think I've addressed the issues you refer, Bryan.

If you request OTP 23, it installs it.
If you request OTP 20, it installs it.
But if you request an invalid Elixir/OTP combo, it'll fail visibly, as per what you wrote. (we can't have a "generic" Elixir version - i.e. the one from the `.zip` without `otp`).

We need to return the version only, without OTP, since that's what the installer script uses. It's appended in the `installElixir` from `installer.js`.

**Comment by paulo-ferraz-oliveira** [comment]
I've pushed https://github.com/erlef/setup-elixir/pull/9/commits/50690edfcc2287489893e2a3f1ff51683b62057e to hopefully increase readability.

Stuff in that commit:
* we drop the concept of `-otp-` (major) in the installer function and move it up (since it was causing confusion upon reasoning on why a given version wasn't available)
* we get rid of conditionals as much as possible, since these weren't helping reason around the issues
* we move `return`s to the end of functions (especially when it's possible they're before `throw`)
* we have consumers and producers name variables mostly the same, so it's easier to follow the code flow

File: src/setup-elixir.js [hunk 12]
```diff
@@ -1,117 +1,193 @@
...
+      `Requested Elixir version (from spec ${exSpec}) not found in build listing ` +
+        JSON.stringify(elixirBuildsListing),
+    )
+  }
+  const exVersion = `v${version}`
+  const otpMatch = otpVersion.match(/^OTP-([^\.]*)/)
+  let elixirVersion
 
-  if (otpMatch != null && versions.get(gitRef).includes(otpMatch[0])) {
-    return [gitRef, otpMatch[0]]
```
Comment (starbelly) [inline src/setup-elixir.js:91]: Excellent commentary, this will help everyone going forward 💯

**Comment by starbelly** [comment]
As FYI, I've made a branch on erlef/website to actually test @paulo-ferraz-oliveira's fork : https://github.com/erlef/website/runs/2170116282?check_suite_focus=true

Can adjust to do a big matrix in a bit.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira it looks like master, maint-23, etc. is not working : https://github.com/starbelly/test-setup-elixir/runs/2170727002?check_suite_focus=true see `Build (ubuntu-16.04, master, 1.9.4)` for an example : 


```shell
Run paulo-ferraz-oliveira/setup-elixir@adapt-for-rebar3
  with:
    otp-version: master
    elixir-version: 1.9.4
    install-hex: true
    install-rebar: true

(node:3389) UnhandledPromiseRejectionWarning: Error: Requested Erlang/OTP version (from spec master) not found in build listing {"remote":"https://repo.hex.pm/builds/otp/ubuntu-16.04/builds.txt"}
    at getOTPVersion (/home/runner/work/_actions/paulo-ferraz-oliveira/setup-elixir/adapt-for-rebar3/dist/index.js:4761:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async installOTP (/home/runner/work/_actions/paulo-ferraz-oliveira/setup-elixir/adapt-for-rebar3/dist/index.js:4683:22)
(node:3389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by paulo-ferraz-oliveira** [comment]
> @paulo-ferraz-oliveira it looks like master, maint-23, etc. is not working

Was it before? I can reinstate behaviour, in that case.

**Comment by paulo-ferraz-oliveira** [comment]
In any case, let me ask you (@starbelly) and @ericmj to re-review the regexp, lest we miss something there, to start with.

| What | Regexp |
|-|-|
| Elixir | `^v(\d+\.\d+\.\d+(?:-.+)?)` |
| Elixir/OTP major | `^OTP-([^\.]*)` |
| Erlang/OTP (from listing) | `^OTP-([\.\drc\-]+)` |
| Elixir version (from listing) | `^(v\d+\.\d+\.\d+(?:-.+)?)-otp-(\d+)` | `^([^-]+)-otp-(\d+)` |
| `rebar3` (from listing) | `^([\.\d]+)` |

**Comment by ericmj** [comment]
> Was it before? I can reinstate behaviour, in that case.

Yes, we need to keep supporting this.

**Comment by paulo-ferraz-oliveira** [comment]
> > Was it before? I can reinstate behaviour, in that case.
> 
> Yes, we need to keep supporting this.

More important, IMO, than just keeping support (which I agree we should) is to also move further, by broadening our scope (everything that was there + more). Some regexp seem broken/incomplete, as were some tests and/or lack of them. @ericmj, if you have the time, I'd ask you to review the table above so we can cover all the bases. 👍 

I'm not aware of anything else that's missing, but would gladly discuss it.

**Comment by paulo-ferraz-oliveira** [comment]
I'll want to:

- [ ] add a test to go through the build listings and make sure our regexps cover all lines (this mighty imply having the regexp in a function or so).

**Comment by ericmj** [comment]
I don't know what the context of the regexes are. Are they from the code base or are they the version strings we are supposed to support?

**Comment by paulo-ferraz-oliveira** [comment]
> I don't know what the context of the regexes are. Are they from the code base or are they the version strings we are supposed to support?

Sure, my bad. I added a bit of text to the table. Those are the regexps as used by the code to find stuff while parsing the listings, but more generically they attempt at representing the way the different pieces are actually versioned.

**Comment by ericmj** [comment]
What's the reason for filtering certain branches? I don't think we should try to predict what builds will provided so we should support any branch name.

**Comment by paulo-ferraz-oliveira** [comment]
> What's the reason for filtering certain branches? I don't think we should try to predict what builds will provided so we should support any branch name.

We're not filtering "branches", but "versions" (that's what I assumed the `builds.txt` was doing). In any case, I'm just seemingly following what I assumed was in place; stuff like https://github.com/erlef/setup-elixir/blob/main/src/setup-elixir.js#L115. I don't mind the regexp is MUCH more relaxed, though, and the previous table would thus become:

| What | Regexp (as currently found in this PR's code base) | What the Regexp could/should be |
|-|-|-|
| Elixir | `^v(\d+\.\d+\.\d+(?:-.+)?)` | `^([^ ]+ )` (while testing with and without `v`) |
| Elixir/OTP major | `^OTP-([^\.]*)` | should be an input from an output from function `installOTP` |
| Erlang/OTP (from listing) | `^OTP-([\.\drc\-]+)` | `^([^ ]+ )` (while testing with and without `OTP-`) |
| Elixir version (from listing) | `^(v\d+\.\d+\.\d+(?:-.+)?)-otp-(\d+)` _or_ `^([^-]+)-otp-(\d+)` | Reuse "Elixir" |
| `rebar3` (from listing) | `^([\.\d]+)` | no match required, since releases are well identified |

**Comment by ericmj** [comment]
> that's what I assumed the builds.txt was doing

`builds.txt` is a listing of what builds are currently provided, but builds may be added and removed from it any time so we shouldn't base regexs on what is currently in the file.

> In any case, I'm just seemingly following what I assumed was in place; stuff like https://github.com/erlef/setup-elixir/blob/main/src/setup-elixir.js#L115

Here we are removing `OTP-` so that users can specify their version as `21.2.3` instead of `OTP-21.2.3`. But in the `if` below we also accept names that do not start with `OTP-`.

> Another example: https://github.com/erlef/setup-elixir/blob/main/src/setup-elixir.js#L135 already filters input, but it's probably not required (easier code and easier to reason about which build are available).

On the line below we accept any version name. The intention is not to filter here, we are separating the elixir version component and the otp version component from the string.

**Comment by paulo-ferraz-oliveira** [comment]
> builds.txt is a listing of what builds are currently provided, but builds may be added and removed from it any time so we shouldn't base regexs on what is currently in the file.

Sure, which is why I propose an even further relaxed regexp of "everything until the first space", where the only assumption is the file format will not change, an assumption already in place for the current code.

> Here we are removing OTP- so that users can specify their version as 21.2.3 instead of OTP-21.2.3. But in the if below we also accept names that do not start with OTP-.

I know, and understand, but not everything will be a valid version, right? e.g. one that's not in the file (which is why now we crash). Would it not make sense to be more relaxed in the matching here, as well?

> On the line below we accept any version name. The intention is not to filter here, we are separating the elixir version component and the otp version component from the string.

Sure. Again, understood, but I think we'd benefit from a more relaxed approach, in any case. As you stated, it's probably the file contents change (including the version format, not controlled by us), but it's less likely the file's format changes, right?

I'll propose a new approach to the regex and let you decide, so you have a term of comparison.

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, I ended up simplifying the regexp, but not as much as I wanted/thought it would be possible. What I aimed for was complete coverage of the existing build listing (but not making many assumptions). I also added a ton of version combos so we can test it as much as possible. Do let me know if you want a specific version combo (semver, master, whatever, ...) so I can update the tests with that.

**Comment by paulo-ferraz-oliveira** [comment]
@eric: https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2195384705?check_suite_focus=true#step:3:11 seems to be the OK version for 19.3.6.9.

But still Elixir complains at boot, a few lines below.

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, I eventually found the error to be Erlang installed in the container at `/usr/bin/erl` and the bad path manipulation in this pull request (now fixed[1]) was causing it to be used instead of the installed Erlang.

---

[1] In the `main` action you're prepending to the path; I was appending to it (I wasn't aware - at all - that Erlang was installed by default in Ubuntu).

**Comment by paulo-ferraz-oliveira** [comment]
Here's a list of the previously failing combos showing that now some pass: https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2197844972?check_suite_focus=true. (the ones failing, in 18.04 are ALL `ssl`-related).

Also, I've changed the min. Elixir version of the test-project to 1.0? It was preventing functioning CI tests from running.

**Comment by starbelly** [comment]
> Also, I've changed the min. Elixir version of the test-project to 1.0? 

That makes sense, since elixir has to support all the way back to 1.0

**Comment by paulo-ferraz-oliveira** [comment]
This is ready for review.

File: dist/.github/workflows/test.yml [hunk 13]
```diff
@@ -37,6 +47,44 @@ jobs:
...
+            otp-version: '23.1'
+          - elixir-version: 'v1.8-otp-21'
+            otp-version: '^22.3'
+          - elixir-version: 'v1.10-otp-21'
+            otp-version: 'OTP-21.x'
+          - elixir-version: 'v1.x'
+            otp-version: 'master'
+          - elixir-version: 'v1.6.x-otp-20'
+            otp-version: '21.1'
+          - elixir-version: 'v1.11.0-rc.0-otp-23'
```
Comment (starbelly) [inline dist/.github/workflows/test.yml:82]: This is the only part I don't understand. I'm not sure this was supported before, but I don't have strong feelings about either.  It may be best if we don't document this, that said, but yeah, no strong feelings. Am fine with it myself

**Review by starbelly — APPROVED** [review]
I think this has been a big effort and I think the fallout is beautiful. It is extremely well tested (and we actually now see when the tests fail), the js code is so much easier to follow, bugs were found and squashed. All of these improvements will make supporting this 💯 easier. Thus I approve 🚀 

I do think @ericmj needs to take a pass as well before we merge.

File: dist/.github/workflows/test.yml (hunk 13 above)
Comment (paulo-ferraz-oliveira) [reply dist/.github/workflows/test.yml:82]: We don't need to document it. It actually isn't in the `README.md`. I added it to/kept it in the tests because I expect it to work 😄 , but I can take it out if you prefer.

I also prefer (and that's what we recommend) to use simple versions like 1.0.0, for `rebar3`, Elixir and Erlang/OTP, and those, too, will work.

Are you specifically talking about the `rc-` part of the `otp-` part? Because for `rc-` I see real value; I want to be able to preemptively test my builds with e.g. 24.0-rc2 (out today 🎉).

Comment (starbelly) [reply dist/.github/workflows/test.yml:82]: otp part, not the rc part, indeed.

Comment (paulo-ferraz-oliveira) [reply dist/.github/workflows/test.yml:82]: Yeah. I can remove the `-otp-` if you prefer, but I imagine it doesn't hurt. @ericmj?

Comment (ericmj) [reply dist/.github/workflows/test.yml:82]: I would say remove it because there should be no reason to set it manually.

Comment (paulo-ferraz-oliveira) [reply dist/.github/workflows/test.yml:82]: I'll make a separate commit to remove the possibility to have `OTP-` as a prefix in Erlang/OTP versions, too. This seems consistent with your request. If it's not something you guys prefer I should easily be able to rollback.

File: __tests__/setup-elixir.test.js [hunk 14]
```diff
@@ -1,21 +1,178 @@
...
+    (err) => {
+      assert.ok(err instanceof Error)
+      return true
+    },
+    `Installing rebar3 ${r3Version} is supposed to fail`,
+  )
+}
+
+async function testOTPVersions() {
+  const otpBuildsListing = listing('otp_builds.txt')
```
Comment (ericmj) [inline __tests__/setup-elixir.test.js:80]: Since we require network connection for other tests what about dropping these files and fetching the actual files for simplicity. That way we will also catch any issues with changes to the files.

File: src/install-elixir [hunk 15]
```diff
@@ -2,9 +2,23 @@
...
+rm -rf "${DIR_FOR_BIN}"
+wget -q -O "${FILE_OUTPUT}" "https://repo.hex.pm/builds/elixir/${FILE_INPUT}"
+mkdir -p "${DIR_FOR_BIN}"
+unzip -q -d "${DIR_FOR_BIN}" "${FILE_OUTPUT}"
+rm -f "${FILE_OUTPUT}"
+echo "$(pwd)/${DIR_FOR_BIN}/bin" >> "$GITHUB_PATH"
+echo "Where is Erlang/OTP?"
+which erl
+echo "Installed Erlang/OTP version follows"
+$(which erl) -version
```
Comment (ericmj) [inline src/install-elixir:22]: We shouldn't do the erlang checks here since `install-otp` do them.

File: src/installer.js [hunk 16]
```diff
@@ -1,32 +1,100 @@
...
+        reject(err)
+      })
+  })
+}
+
+function checkPlatform() {
+  if (
+    process.platform !== 'linux' &&
+    process.env.CI_TEST_ENV !== 'test' &&
+    process.platform !== 'darwin'
```
Comment (ericmj) [inline src/installer.js:88]: This check should not be here, right?

File: src/installer.js [hunk 17]
```diff
@@ -1,32 +1,100 @@
...
+        )
+        reject(err)
+      })
+  })
+}
+
+function checkPlatform() {
+  if (
+    process.platform !== 'linux' &&
+    process.env.CI_TEST_ENV !== 'test' &&
```
Comment (ericmj) [inline src/installer.js:87]: What is this check doing?

File: src/setup-elixir.js [hunk 18]
```diff
@@ -1,97 +1,356 @@
...
 
-main().catch(err => {
+try {
+  main().catch((err) => {
+    core.setFailed(err.message)
+  })
+} catch (err) {
   core.setFailed(err.message)
-})
+}
```
Comment (ericmj) [inline src/setup-elixir.js:17]: What is the `try {} catch {}` catching that `catch((err) => {})` doesn't catch?

File: src/setup-elixir.js [hunk 19]
```diff
@@ -1,97 +1,356 @@
...
-  checkPlatform()
+  const maybePlatformIsOKError = installer.checkPlatform()
+  if (maybePlatformIsOKError !== 'ok') {
+    throw new Error(maybePlatformIsOKError)
+  }
 
   const osVersion = getRunnerOSVersion()
+  const otpBuildsListing = {
+    remote: `https://repo.hex.pm/builds/otp/${osVersion}/builds.txt`,
+  }
```
Comment (ericmj) [inline src/setup-elixir.js:28]: This seems like unnecessary complexity, can we pass the strings directly without wrapping in an object?

File: src/setup-elixir.js [hunk 20]
```diff
@@ -1,97 +1,356 @@
...
+            })
+            const shouldMixHex = core.getInput('install-hex', {required: false})
+            await mix(shouldMixHex, 'hex').catch((err) => {
+              throw err
+            })
+          }
+        })
+        .catch((err) => {
+          throw err
+        })
```
Comment (ericmj) [inline src/setup-elixir.js:53]: I don't know javascript very well, but is there any way we can avoid these `.catch((err) => { throw err })` everywhere? In the past we didn't use promises directly and instead only relied on the `async / await` syntax, can we still do that?

File: src/setup-elixir.js [hunk 21]
```diff
@@ -1,97 +1,356 @@
...
+      const elixirBuildsListing = {
+        remote: 'https://repo.hex.pm/builds/elixir/builds.txt',
+      }
+      const elixirSpec = core.getInput('elixir-version', {required: false})
+      await maybeInstallElixir(elixirSpec, otpVersion, elixirBuildsListing)
+        .then(async (elixirInstalled) => {
+          if (elixirInstalled === true) {
+            const shouldMixRebar = core.getInput('install-rebar', {
+              required: false,
+            })
```
Comment (ericmj) [inline src/setup-elixir.js:41]: Is the default still to install rebar and hex and if elixir was installed?

File: src/setup-elixir.js [hunk 22]
```diff
@@ -1,97 +1,356 @@
...
+      resolve(false)
+    }
+  })
+}
 
-  process.env.PATH = `${process.env.RUNNER_TEMP}/.setup-elixir/elixir/bin:${process.env.RUNNER_TEMP}/.setup-elixir/otp/bin:${process.env.PATH}`
+function mix(shouldMix, what) {
+  return new Promise(async (resolve, reject) => {
+    if (shouldMix) {
+      console.log(`##[group]Mixing local.${what}`)
```
Comment (ericmj) [inline src/setup-elixir.js:129]:
```suggestion
      console.log(`##[group]Running mix local.${what}`)
```

File: src/setup-elixir.js [hunk 23]
```diff
@@ -103,71 +362,48 @@ function getVersionFromSpec(spec, versions) {
...
-    .split('\n')
-    .forEach(line => {
-      const match =
-        line.match(/^(v\d+\.\d+\.\d+(?:-.+)?)-otp-(\d+)/) ||
-        line.match(/^([^-]+)-otp-(\d+)/)
+function get(urlOrFile) {
+  return new Promise(async (resolve, reject) => {
+    if (urlOrFile.remote) {
+      const req = https.get(urlOrFile.remote, {
+        headers: {'user-agent': 'setup-elixir'},
```
Comment (ericmj) [inline src/setup-elixir.js:379]: Nice, this should help with stats.

**Review by ericmj — COMMENTED** [review]
I've done a second review. Left a few comments, mostly questions, but overall it's a great. Particularly like the extra attention given to testing, we will be more comfortable doing changes in the future with the extensive testing.

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (paulo-ferraz-oliveira) [reply __tests__/setup-elixir.test.js:80]: We can do that, sure. I'm just afraid that changing some of these will actually lead to different test results (e.g. I can't use `1` as a version since that'll yield different results as soon as `builds.txt` changes), but I can do it, no prob.

File: src/install-elixir (hunk 15 above)
Comment (paulo-ferraz-oliveira) [reply src/install-elixir:22]: I understand that, but since it bit me, I preferred to be conservative. Let's say the path is badly manipulated in the meantime (as was the case during development).

File: src/installer.js (hunk 16 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js:88]: It should IMO. Locally I should be able to test on a Mac (especially since it works), but if you prefer I can take it out and only assume Linux based testing (will be kinda hindering for updating though - since I have to add it for testing, and remove it before pushing).

File: src/installer.js (hunk 17 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js:87]: Making sure it's either Linux or Darwin in testing. I'll revert it. I don't want the PR to be blocked for this.

File: src/setup-elixir.js (hunk 18 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: 😄 exceptions, surely. I ran the tests without try/catch and get (UnhandledExceptionWarning). `.catch` catches stuff inside `async`, which is not the case for `checkPlatform`. You want me to change something here?

File: src/setup-elixir.js (hunk 19 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: You can, if you decide that `builds.txt` is always remote. Otherwise, I have it there for testing (which uses a string, not a URL). I could also go for "parsing as URL", but decided this would be more explicit. What do you prefer?

File: src/setup-elixir.js (hunk 20 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: We could, but, as stated before, we were not handling promise returns that eventually ended up hiding issues. Let me know what you prefer and I can do that. I also don't like this syntax very much, but it's what's working.

File: src/setup-elixir.js (hunk 21 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: I don't completely get the question, since I believe there's an extra "and" there, but if I get it right, yes, `mix` should only execute if Elixir is installed properly. Did I assume this wrong and it should be installed whenever?

File: src/setup-elixir.js (hunk 22 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:134]: Sure.

File: src/setup-elixir.js (hunk 23 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:385]: I didn't actually do it for that 😄, but because local tests failed. I'm glad it helps in that case, too.

File: src/installer.js (hunk 16 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js:88]: I've reverted this change. It'll simply imply more force-pushes on my behalf to get stuff running properly. No biggie, though.

File: src/installer.js (hunk 17 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js:87]: This is reverted.

File: src/setup-elixir.js (hunk 22 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js:134]: This has now been pushed. Tests are still failing on purpose, because I wanna make sure consumption is eased, by:
1. having use fail fast, when expected,
2. not having unhandled exceptions.

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (paulo-ferraz-oliveira) [reply __tests__/setup-elixir.test.js]: f79efb2: done. I'm afraid tests lost some quality, though, as per what I explained previously (if depending on a dynamic environment we can't actually be sure of what'll happen when we do stuff like `'^1.10'`)

File: src/setup-elixir.js (hunk 19 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: f79efb2

File: src/install-elixir (hunk 15 above)
Comment (paulo-ferraz-oliveira) [reply src/install-elixir]: eb8fb56: done. I prefer to move forward than to see the pull request declined because of this detail. If it bites us again, in the future, we'll just deal with that.

File: src/setup-elixir.js (hunk 18 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: In any case, more recently, I moved main from `async` to `Promise` which reverts this change.

File: src/setup-elixir.js (hunk 20 above)
Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: I'll revert everything back to `async`, and potentially keep previously existing hidden bugs. Expect a couple of hours of implementation and testing, though, since I had a hard time getting to the point I'm at.

Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: This'll most likely also move us to an exception-based flow style of coding, which I found particularly hard to follow while adapting this. (still doing the move, though)

Comment (paulo-ferraz-oliveira) [reply src/setup-elixir.js]: I moved everything from `Promise` to `async` (include `Promise`-based code that previously existed also, for consistency). We know have many `throw`s where we didn't, but less `catch`, which seems to be what was bothering you. Lemme know if this approach is viable.

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj: `dist`, as-is (`main`) contains https://github.com/erlef/setup-elixir/tree/main/dist/.github/workflows. I'm unsure whether these files actually make a difference. (the matchers I can understand) I'm wondering if these (`.yml`) get copied because `elixir.json` is inside `.github` and that one (`.json`) is referenced by `index.js`.

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (ericmj) [reply __tests__/setup-elixir.test.js]: We can do the tests on version ranges that are no longer supported and won't be updated.

File: src/installer.js (hunk 16 above)
Comment (ericmj) [reply src/installer.js]: How does it work on mac if erlang is compiled against linux?

File: src/installer.js (hunk 17 above)
Comment (ericmj) [reply src/installer.js]: I was asking specifically about `process.env.CI_TEST_ENV !== 'test'`. What does that check do?

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (paulo-ferraz-oliveira) [reply __tests__/setup-elixir.test.js]: That's what supposedly did, with this change. In any case, to be completely sure, I'd have to know exactly what isn't supported. We can deal with mishaps, if any, later, if new versions come out that change test results.

File: src/installer.js (hunk 16 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js]: `setup-elixir.test.js` presents two types of tests:
* failing installs (e.g. inexisting file or input not accepted)
* version-based tests (testing against semver)
None of these require the builds to actually run, since we're interested in other conditions, so there's no difference in running them in Linux and Mac, except that without allow `process.platform` `darwin` you can't actually properly run these locally.

File: src/installer.js (hunk 17 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js]: Nothing, anymore, since it was eventually removed. At a given point in time I had it defined as an env. variable.

**Comment by paulo-ferraz-oliveira** [comment]
Is anything still missing?

File: src/installer.js (hunk 16 above)
Comment (ericmj) [reply src/installer.js]: In that case I would recommend unit testing that functionality directly so it doesn't go through this check.

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (ericmj) [reply __tests__/setup-elixir.test.js]: You can find supported Elixir versions here: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#content. I would guess Erlang has similar documentation.

Comment (ericmj) [reply __tests__/setup-elixir.test.js]: OT: when you resolve conservations after responding it is very hard to find your replies.

Comment (paulo-ferraz-oliveira) [reply __tests__/setup-elixir.test.js]: > OT: when you resolve conservations after responding it is very hard to find your replies.

Sorry about that. It sometimes happens. Is anything missing regarding this conversation, in particular?

File: src/installer.js (hunk 16 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js]: We have e.g. https://github.com/erlef/setup-elixir/pull/9/files#diff-3e35f8d82312f568d749abab56e430c703198c68e3b8468454005ac9bc806797R10. Do you prefer me to test 
```erlang
exec(path.join(__dirname, 'install-otp'), [
    osVersion,
    otpVersion,
  ])
```
directly? (as is, now, it's only affecting local testing, not remote)

Comment (paulo-ferraz-oliveira) [reply src/installer.js]: I'll move on this front, lest the answer is "yes" and then I lose the opportunity for a further review. 😄

**Comment by paulo-ferraz-oliveira** [comment]
Now I should rebase on top of `main`.

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (paulo-ferraz-oliveira) [reply __tests__/setup-elixir.test.js]: This is Erlang/OTP testing: https://github.com/erlef/setup-beam/pull/9/files#diff-c76af13c0a24fd165fe6700b8b1254b6a48a60b9ddfcb39dcad476a725f8106bR84 (all results belong to no-longer-supported versions)
This is Elixir testing: https://github.com/erlef/setup-beam/pull/9/files#diff-c76af13c0a24fd165fe6700b8b1254b6a48a60b9ddfcb39dcad476a725f8106bR109 (all results belong to no-longer-supported versions)
This is `rebar3` testing: https://github.com/erlef/setup-beam/pull/9/files#diff-c76af13c0a24fd165fe6700b8b1254b6a48a60b9ddfcb39dcad476a725f8106bR133 (all results belong to no-longer-supported versions)

I assume we're good (?)

File: src/installer.js (hunk 16 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js]: I've removed the validation (33c64db) since if we're not doing it for tests there's no need to do it any way (since `setup-elixir.js` already does it at start).

File: __tests__/setup-elixir.test.js (hunk 14 above)
Comment (ericmj) [reply __tests__/setup-elixir.test.js]: All good!

File: src/installer.js [hunk 24]
```diff
@@ -1,32 +1,46 @@
...
- * @param {string} otpMajor
+ * @param {string} elixirVersion
  */
-async function installElixir(version, otpMajor) {
-  if (process.platform === 'linux') {
-    const otpString = otpMajor ? `-otp-${otpMajor}` : ''
-    await exec(path.join(__dirname, 'install-elixir'), [version, otpString])
-  }
+async function installElixir(elixirVersion) {
+  return await exec(path.join(__dirname, 'install-elixir'), [elixirVersion])
```
Comment (ericmj) [inline src/installer.js:23]: I think `async` + `return await` is redundant unless you do something like wrap `try .. catch`.

Comment (paulo-ferraz-oliveira) [reply src/installer.js:23]: Sure. I'll remove it.

Comment (paulo-ferraz-oliveira) [reply src/installer.js:23]: ... though keeping it is not hurtful; I did it, by principle, elsewhere, then must have replicated it here for no special reason.

Comment (paulo-ferraz-oliveira) [reply src/installer.js]: 3c2d3a5

**Comment by starbelly** [comment]
It seems like we've got everything ironed out for the most part now. There's probably lots of little things that can be improved on , but I'm not sure this PR is the place for those anymore. Other little things I believe can be handled in subsequent PRs and I think we can and should do some second passes, but the amount of churn on this PR has peaked IMO and is at least for me becoming harder to follow. 
Unless there's something egregious can we move forward with this @ericmj ?

File: src/installer.js (hunk 24 above)
Comment (ericmj) [reply src/installer.js]: Is `async` and a single `await` also redundant?

**Review by ericmj — APPROVED** [review]

File: src/installer.js (hunk 24 above)
Comment (paulo-ferraz-oliveira) [reply src/installer.js]: Hm... that's a good question. I've always used `async` so that consumers `await` on my function. If `exec` is `async`, though, without `await` the function should just return "instantaneously".

Comment (paulo-ferraz-oliveira) [reply src/installer.js]:
```javascript
async function first() {
    await exec()
    console.log('first')
}

async function exec(Cmd) {
    return new Promise((res, rej) => {
        setTimeout(function() {
            res(console.log('do I show up before "first"?'))
        }, 100)
    })
}

first()
```

If your Promise is not synchronous, an `await` is required. 

This is what MDN states "The body of an async function can be thought of as being split by zero or more await expressions. Top-level code, up to and including the first await expression (if there is one), is run synchronously. In this way, an async function without an await expression will **run** synchronously. If there is an await expression inside the function body, however, the async function will always **complete** asynchronously."

**Comment by paulo-ferraz-oliveira** [comment]
Squashed and force-pushed. Waiting on CI.
