### PR TITLE
Wrong Erlang/OTP version `maint-x` matched when requesting `x`

### LINKED ISSUE #120: Wrong Erlang/OTP version `maint-x` matched when requesting `x`
It seems that OTP 25 is built without `KERL_BUILD_DOCS=yes`
This breaks tests in [elixir_sense](https://github.com/elixir-lsp/elixir_sense/runs/6676822770?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Don't take `maint-` -prefixed versions into account unless they're asked for it specifically.
At the same time, while fetching versions, make sure we identify them better so that `25` does not end up pulling `maint-25` instead of `OTP-25.0`, as it should.

Closes #120.

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -6191,12 +6191,12 @@ async function maybeInstallRebar3(rebar3Spec) {
 
 async function getOTPVersion(otpSpec0, osVersion) {
   const otpVersions = await getOTPVersions(osVersion)
-  const otpSpec = otpSpec0.match(/^(OTP-)?([^ ]+)/)
+  const otpSpec = otpSpec0.match(/^(OTP-|maint-)?([^ ]+)/)
```
Comment (starbelly) [inline dist/index.js:6194]: I wonder if this should be case insensitive, thoughts?

File: dist/index.js [hunk 2]
```diff
@@ -6191,12 +6191,12 @@ async function maybeInstallRebar3(rebar3Spec) {
...
   let otpVersion
   if (otpSpec[1] && !isStrictVersion()) {
     throw new Error(
       `Requested Erlang/OTP version (${otpSpec0}) ` +
-        "should not contain 'OTP-'",
+        "should not contain 'OTP-, or maint-'",
```
Comment (starbelly) [inline dist/index.js:6199]: To be sure I'm following along here, we're saying if the string you provided ends up matching two groups (`OTP-` or `maint-`) and version number, but you did not specify use strict versioning, we throw, is that all correct?

File: dist/index.js (hunk 1 above)
Comment (paulo-ferraz-oliveira) [reply dist/index.js:6194]: In which case do you expect this to change? I don't mind making it insensitive to case, but it's worked thus far...

**Comment by paulo-ferraz-oliveira** [comment]
I'm going ahead with merging this. We can maybe solve the details of your review in an upcoming release, if required.
